//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWproject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class authentificationEntities : DbContext
    {
        public authentificationEntities()
            : base("name=authentificationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RECOVERY> RECOVERY { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
