//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECOVERY
    {
        public int ID { get; set; }
        public Nullable<int> idusername { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<bool> emailsent { get; set; }
        public string token { get; set; }
        public Nullable<bool> completed { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
