//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public int ID { get; set; }
        public string role1 { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
